### PR TITLE
#126: Fixes issues reading/writing typed properties which are uninitialised

### LINKED ISSUE #126: Another one with PHP 7.4
**EDIT: I am so sorry, I was wrong, bug is elsewhere, I did too much code reading without actually testing before...**

Hello, following https://github.com/Ocramius/GeneratedHydrator/issues/118 I stumbled upon yet another PHP 7.4 side effect.

I'm not sure this is really a bug, so I open this issue for discussion.

Considering the following PHP class:

```php
namespace Some\Namespace;

class Foo
{
    public int $bar;
}
```

GeneratedHydrator will generate the following code:

```php
class SomeGeneratedNameForHydrator implements \Zend\Hydrator\HydratorInterface
{
    private $hydrateCallbacks = array(), $extractCallbacks = array();
    function __construct()
    {
        $this->hydrateCallbacks[] = \Closure::bind(static function ($object, $values) {
            if (isset($values['bar']) || $object->bar !== null && \array_key_exists('bar', $values)) {
                $object->bar = $values['bar'];
            }
        }, null, 'Some\\Namespace\\Foo');
        $this->extractCallbacks[] = \Closure::bind(static function ($object, &$values) {
            $values['bar'] = $object->bar;
        }, null, 'Some\\Namespace\\Foo');
    }
    function hydrate(array $data, $object)
    {
        $this->hydrateCallbacks[0]->__invoke($object, $data);
        return $object;
    }
    function extract($object)
    {
        $ret = array();
        $this->extractCallbacks[0]->__invoke($object, $ret);
        return $ret;
    }
}
```

If I attempt an hydration, this will cause the following error:

```
"Typed property Some\Namespace\Foo::$bar must not be accessed before initialization"
```

Problem is that the following line:

```php
            if (isset($values['bar']) || $object->bar !== null && \array_key_exists('bar', $values)) {
                $object->bar = $values['bar'];
            }
```

Will cause that.

Since that `$bar` is mandatory, and has no default, we could safely write:

```php
            if (isset($values['bar'])) {
                $object->bar = $values['bar'];
            }
```

instead, and that would work.

Now, I cannot see any regression because of this code  let me explain: let's consider the use case I'm working with, I always hydrate empty objects, created without a constructor, the following way:

```php

$ref = new \ReflectionClass(Some\Namespace\Foo::class);
$object = $ref->newInstanceWithoutConstructor();

$class = $someHydratorFactory->getHydratorClass();

(new $class())->hydrate($object, [
    'bar' => 12,
]);
```

In this case, everything would be fine with the proposed generated code modification.

For other use cases such as:

```php
namespace Some\Namespace;

class Foo
{
    public int $bar;

    public function __construct(int $bar)
    {
        $this->bar = $bar;
    }
}
```

Then:

```php
$object = new Some\Namespace\Foo(7);

$class = $someHydratorFactory->getHydratorClass();

(new $class())->hydrate($object, [
    'bar' => 12,
]);
```

Should work as well, meaning that `$bar` value after hydration would be 12 as well.

If I remeber correctly, `$object->bar !== null && \array_key_exists('bar', $values)` was added so that `null` value can be explicitely set by the hydrator.

Devil here is in `null` handling, in this case (non nullable property), an explicit null value would be erroneous since that the target property can not be null and raise an error while attempt to set it explicitely. I guess we can safely remove the null handling then.

I can see one use case we miss: if the user do this:

```php
$object = new Some\Namespace\Foo(7);

$class = $someHydratorFactory->getHydratorClass();

(new $class())->hydrate($object, [
    'bar' => null,
]);
```

Then `isset($values['bar'])` will miss that value is here, and is null. Should we do some kind of validation here, such as:

```php
if (\array_key_exists($values['bar'])) {
    if (null === $values['bar']) {
        throw new HydratorKindOfException("Some\Namespace\Foo::\$bar cannot be null");
    }
    $object->bar = $values['bar'];
}
```

Or just generate:

```php
if (\array_key_exists($values['bar'])) {
    $object->bar = $values['bar'];
}
```

And let PHP raise the exception itself? I think this option is the best, `\array_key_exists()` has now a specific OPCode for itself, and the performance impact would be, I guess, meaningless. Maybe it needs testing thought, but semantically, this is most accurate solution, and it solves all use cases altogether.

I will open a PR with tests and the modified code.

### PR DESCRIPTION
**Pull request by carnage**
#126 documents an issue with the generated hydrator failing with an error when trying to hydrate an object containing typed properties when a typed property is not present in the data array passed to the hydrator, contains no default value and cannot be null. 

The fix is to check that the property isset before attempting to do the null check (hydration) or read from the property (extraction). Extraction behaviour for an unset property is not to include the property in the extracted payload; this is to ensure that the behaviour of chained $hydrator->extract() and $hydrator->hydrate() calls continues to work as expected since keeping the property in the array but leaving it null would cause the hydrate call to attempt to set the property to null, this is undesirable as the property type definition doesn't include null and would cause an error.

Have targetted against 4.1.x as this is a bug introduced by PHP 7.4 and this is the most recent version which supports PHP 7.4

This code could be considered a BC break as an operation which previously resulted in an error will now operate correctly, however there are very few scenarios that I can think of where this would cause someone an issue, since using hydration as a means of data validation would be a pretty suspect use case. 

Fixes #126

### CODE REVIEW

File: tests/GeneratedHydratorTest/Functional/HydratorFunctionalTest.php [hunk 1]
```diff
@@ -103,6 +103,30 @@ public function testHydratorWillNotRaisedUnitiliazedTypedPropertyAccessError():
         ], $hydrator->extract($instance));
     }
 
+    /**
+     * Ensures that the hydrator will not attempt to read unitialized PHP >= 7.4
+     * typed property, which would cause "Uncaught Error: Typed property Foo::$a
+     * must not be accessed before initialization" PHP engine errors.
+     *
+     * @requires PHP >= 7.4
```
Comment (Ocramius) [inline tests/GeneratedHydratorTest/Functional/HydratorFunctionalTest.php]: TBH, let's drop 7.3 and earlier from the package

**Review by Ocramius — APPROVED** [review]
Besides minor cleanup (let's move on from 7.3), LGTM :+1:

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
Just CS fixes left 👍

File: src/GeneratedHydrator/CodeGenerator/Visitor/HydratorMethodsVisitor.php [hunk 2]
```diff
@@ -141,8 +146,19 @@ private function replaceConstructor(ClassMethod $method): void
...
+                $indent        = $requiresGuard ? '        ' : '    ';
+
+                if ($requiresGuard) {
+                    $bodyParts[] = '    if (isset($object->' . $propertyName . ')) {';
+                }
+
+                $bodyParts[]  = $indent . "\$values['" . $propertyName . "'] = \$object->" . $propertyName . ';';
+
+                if ($requiresGuard) {
+                    $bodyParts[] = '    }';
```
Comment (carnage) [inline src/GeneratedHydrator/CodeGenerator/Visitor/HydratorMethodsVisitor.php]: not actually sure what the CS rules wanted me to fix here. Surely it doesn't want to invert the condition to put a continue here and then make the assignment outside of the if?

Comment (Ocramius) [reply src/GeneratedHydrator/CodeGenerator/Visitor/HydratorMethodsVisitor.php]: Yeah, I think it wants a `continue;` or such - conditionals inside a `foreach` are (rightfully) frowned upon by the current CS rules

This is what's left:

```
Error: Equals sign not aligned correctly; expected 1 space but found 2 spaces
Error: Use early exit to reduce code nesting.
```

**Review by Ocramius — CHANGES_REQUESTED** [review]

File: src/GeneratedHydrator/CodeGenerator/Visitor/HydratorMethodsVisitor.php (hunk 2 above)
Comment (carnage) [reply src/GeneratedHydrator/CodeGenerator/Visitor/HydratorMethodsVisitor.php]: That would be objectively worse code; I've extracted it into a method instead

**Comment by carnage** [comment]
@Ocramius I've rebased this from the latest branch; hopefully that'll resolve the outstanding test coverage issue it was having can you OK the pipeline run?

**Review by Ocramius — APPROVED** [review]
LGTM :ship: 

Thanks @carnage

**Comment by Ocramius** [comment]
```
 Error: ] The minimum required MSI percentage should be 95%, but actual is       
         94.04%. Improve your tests!                                            
```

Sounds like the newly introduced code has mutations to be handled via new tests :thinking: 

Also, a `phpcbf` run is needed

**Comment by carnage** [comment]
Not entirely sure how to resolve that tbh; the new code does have test coverage. So it's a bit confusing that it's failing on that metric.

**Comment by Ocramius** [comment]
Looking at test failures, I think it's not verifying the generated code output.

**Comment by carnage** [comment]
It isn't verifying the generated code output; it's verifying the functioning of the generated code. Most if not all the escaped mutants are basically coding standards failures. eg it's putting whitespace at the end of a line instead of the start by flipping the order of a concat. 

Could add a functional test which runs php cs against the generated code to ensure it matches the standards which would catch the mutants; but I'm not convinced of the value of doing that :thinking:

**Comment by Ocramius** [comment]
It's either testing the code until there's nothing left to test, or simplifying the code until there's no other way to wiggle it.

It's very much true that things like alignment could be removed from the code generator, for example.

**Comment by carnage** [comment]
@Ocramius I've improved the fix here thanks to a suggestion from my apprentice. 

Basically instead of detecting if a property has a type and changing the generated code to add an additional isset, it replaces the !== null check with isset in all cases. This is faster for typed properties and incurs a slight overhead on non-typed properties where the !== null is slightly faster. 

I think this is a reasonable trade off as I'd expect most people to be using typed properties on their data objects that they'll use this on. 

To solve the infection PHP issues I replaced the string concatenation in the new/changed code with sprintf infection can't mutate the sprintf version of the code without breaking the tests. Unlike the concat version where it could move whitespace around without a noticeable effect.

**Comment by pounard** [comment]
Will this change be merged soon ? I'm once again bitten by the unitialized property issue.

**Comment by Ocramius** [comment]
Was on my plate / in background for far too long: thanks @carnage!
